[package]
name = "lethe"
version = "0.1.0"
edition = "2021"

[dependencies]
crypter = { git = "https://github.com/lemosyne/crypter.git" }
hasher = { git = "https://github.com/lemosyne/hasher.git" }
khf = { git = "https://github.com/lemosyne/khf.git" }
kms = { git = "https://github.com/lemosyne/kms.git" }
path_macro = "1.0.0"
rand = "0.8.5"
thiserror = "1.0.40"
